import type { SurfPoint } from './types';

export const kochiPoints: SurfPoint[] = [
  {
    id: 'point-10',
    name: '高知 生見',
    lat: 33.535,
    lon: 134.33,
    bestSwell: 'ESE, SE, SSE, S',
    note: '東洋町、南東がベスト',
    beachFacing: 'SE',
    tideStation: 'muroto',
    bayGeometry: {
      type: 'semi-enclosed',
      openingAngle: 199,
      openingDir: 131,
      openingDirStr: 'SE',
      diffractionFactor: 0.8,
      convergenceFactor: 0.9,
      headlands: [
        { bearing: 297, distanceKm: 2.6, name: '塚崎' },
        { bearing: 287, distanceKm: 2.6, name: '唐人ヶ鼻' },
        { bearing: 246, distanceKm: 4.1, name: '松ヶ鼻' },
        { bearing: 32,  distanceKm: 5.9, name: '乳ノ崎' },
      ],
      obstacles: [
        { type: 'islet', bearing: 283, distanceKm: 1.79, name: '葛島' },
        { type: 'islet', bearing: 350, distanceKm: 2.38, name: '棚碆' },
        { type: 'islet', bearing: 350, distanceKm: 2.57, name: 'ウバエ島' },
        { type: 'islet', bearing: 339, distanceKm: 2.85, name: 'サビ島' },
        { type: 'islet', bearing: 278, distanceKm: 2.94, name: '赤葉島' },
        { type: 'islet', bearing: 340, distanceKm: 3.02, name: '鹿子居島' },
        { type: 'islet', bearing: 337, distanceKm: 3.14, name: 'シシケ碆' },
        { type: 'reef',  bearing: 281, distanceKm: 3.18 },
        { type: 'reef',  bearing: 281, distanceKm: 3.56 },
        { type: 'islet', bearing: 7,   distanceKm: 5.45, name: '二子島' },
      ],
    },
  },
  {
    id: 'point-14',
    name: '高知 尾崎ビーチ',
    lat: 33.367,
    lon: 134.2,
    bestSwell: 'ESE, SE, SSE, S',
    note: '室戸市。太平洋に開けたオープンビーチ。南〜東南東うねりに素直に反応。',
    beachFacing: 'SE',
    tideStation: 'muroto',
    bayGeometry: {
      // 室戸岬北側の直線的な海岸。遮蔽物が少なくほぼオープン。
      // 北側（15°/4km付近）に小さな岬があるが影響は軽微。
      type: 'open',
      openingAngle: 220,
      openingDir: 135,
      openingDirStr: 'SE',
      diffractionFactor: 0.95,
      convergenceFactor: 0.95,
      headlands: [],
      obstacles: [],
    },
  },
  {
    id: 'point-26',
    name: '高知 仁淀川河口',
    lat: 33.45993141538984,
    lon: 133.48098450723376,
    bestSwell: 'SE, SSE, ESE, S',
    note: '土佐市・いの町境。仁淀川河口の河口サンドバー。土佐湾に南東向きに開けた河口ポイント。南東〜南うねりに反応しやすい。',
    beachFacing: 'SE',
    tideStation: 'muroto',
    bayGeometry: {
      // 土佐湾に南東向きに開けたオープンな河口。西側に横浪半島が緩やかな遮蔽。
      type: 'open',
      openingAngle: 200,
      openingDir: 135,
      openingDirStr: 'SE',
      diffractionFactor: 0.9,
      convergenceFactor: 1.0,
      headlands: [
        { bearing: 250, distanceKm: 15.0, name: '横浪半島' },
      ],
      obstacles: [],
    },
  },
  {
    id: 'point-27',
    name: '高知 平野海岸',
    lat: 32.9607181762383,
    lon: 132.99438672679085,
    bestSwell: 'E, ESE, SE, ENE',
    note: '黒潮町。双海の南側に位置する砂浜。海岸線は南北に走り、太平洋に東向きに開けたオープンビーチ。東〜南東うねりに素直に反応。',
    beachFacing: 'E',
    tideStation: 'muroto',
    bayGeometry: {
      type: 'open',
      openingAngle: 210,
      openingDir: 90,
      openingDirStr: 'E',
      diffractionFactor: 0.92,
      convergenceFactor: 1.0,
      headlands: [
        { bearing: 195, distanceKm: 38.0, name: '足摺岬' },
      ],
      obstacles: [],
    },
  },
  {
    id: 'point-28',
    name: '高知 大方浮鞭',
    lat: 33.03428881101668,
    lon: 133.03222962660124,
    bestSwell: 'S, SSE, SSW, SE',
    note: '黒潮町大方。浮鞭海岸。海岸線は東西に走り、太平洋に南向きに開けたオープンビーチ。南うねりに素直に反応。入野海岸と連続する砂浜で、コンスタントにサーフできる高知西部の人気ポイント。',
    beachFacing: 'S',
    tideStation: 'muroto',
    bayGeometry: {
      type: 'open',
      openingAngle: 210,
      openingDir: 180,
      openingDirStr: 'S',
      diffractionFactor: 0.92,
      convergenceFactor: 1.0,
      headlands: [
        { bearing: 197, distanceKm: 42.0, name: '足摺岬' },
      ],
      obstacles: [],
    },
  },
  {
    id: 'point-29',
    name: '高知 入野海岸',
    lat: 33.03200282614476,
    lon: 133.0277639306864,
    bestSwell: 'SE, SSE, ESE, S',
    note: '黒潮町入野。入野松原に面した砂浜。海岸線は北西〜南東に走り、太平洋に南東向きに開けたオープンビーチ。大方浮鞭と連続する長大な砂浜の中央エリア。',
    beachFacing: 'SE',
    tideStation: 'muroto',
    bayGeometry: {
      type: 'open',
      openingAngle: 210,
      openingDir: 135,
      openingDirStr: 'SE',
      diffractionFactor: 0.92,
      convergenceFactor: 1.0,
      headlands: [
        { bearing: 196, distanceKm: 40.0, name: '足摺岬' },
      ],
      obstacles: [],
    },
  },
  {
    id: 'point-30',
    name: '高知 双海海岸',
    lat: 32.97220827207688,
    lon: 132.99979047204062,
    bestSwell: 'S, SSW, SSE, SW',
    note: '黒潮町双海。双海サーフビーチ。太平洋に南向きに開けたビーチ。南うねりに反応しやすい。',
    beachFacing: 'S',
    tideStation: 'muroto',
    bayGeometry: {
      type: 'open',
      openingAngle: 210,
      openingDir: 180,
      openingDirStr: 'S',
      diffractionFactor: 0.92,
      convergenceFactor: 1.0,
      headlands: [
        { bearing: 194, distanceKm: 36.0, name: '足摺岬' },
      ],
      obstacles: [],
    },
  },
  {
    id: 'point-31',
    name: '高知 大岐海岸',
    lat: 32.819547,
    lon: 132.950584,
    bestSwell: 'SE, SSE, S, ESE',
    note: '土佐清水市大岐。足摺岬の北東側に位置する弓形の砂浜。太平洋に東〜南東向きに開けたビーチで、南東〜南うねりに最もよく反応。足摺岬が南西〜西方向を遮蔽するため、その方向のうねりは入りにくい。',
    beachFacing: 'SE',
    tideStation: 'muroto',
    bayGeometry: {
      // 太平洋に東〜南東向きに開いた弓形ビーチ。
      // 足摺岬（約215°/10km）が南西〜西を遮蔽。
      type: 'semi-enclosed',
      openingAngle: 170,
      openingDir: 130,
      openingDirStr: 'SE',
      diffractionFactor: 0.85,
      convergenceFactor: 1.0,
      headlands: [
        { bearing: 215, distanceKm: 10.0, name: '足摺岬' },
      ],
      obstacles: [],
    },
  },
];
